### ISSUE TITLE
[1.15.2] multiparts appear as missing textures

### ISSUE THREAD

**Issue by Jarfeh** [Juuxel/VanillaParts#14]
![2020-03-22_15 51 32](https://user-images.githubusercontent.com/58902941/77263236-22cb7300-6c55-11ea-9ac7-13654566e043.png)

**Comment by Vile135** [comment]
I'm getting the same problem, are you using optifine with this? (+optifabric)

**Comment by RusticKey** [comment]
I'm also using Optifine + Optifabric, and when I disabled them the multiparts work fine. It's another incompatibility with OptiFine and/or OptiFabric I guess.

**Comment by Juuxel** [comment]
Optifine is not supported.
