### ISSUE TITLE
Crash when using mod functionality

### ISSUE THREAD

**Issue by futurenp** [Juuxel/VanillaParts#2]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/13/19 7:28 PM
Description: Batching chunks

java.lang.ClassCastException: net.optifine.override.ChunkCacheOF cannot be cast to net.fabricmc.indigo.renderer.accessor.AccessChunkRendererRegion
	at net.minecraft.class_851.redirect$hookChunkBuildTesselate$zbl000(class_851.java:622)
	at net.minecraft.class_851.method_3652(class_851.java:385)
	at net.minecraft.class_845.method_3615(class_845.java:90)
	at net.minecraft.class_845.run(class_845.java:39)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.class_851.redirect$hookChunkBuildTesselate$zbl000(class_851.java:622)

-- Affected level --
Details:
	All players: 1 total; [class_746['Naterbobber'/3, l='MpServer', x=13.78, y=12.00, z=167.08]]
	Chunk stats: Client Chunk Cache: 1849, 1369
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-8,10,152), Chunk: (at 8,0,8 in -1,9; contains blocks -16,0,144 to -1,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 103897 game time, 6077 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:574)
	at net.minecraft.class_310.method_1587(class_310.java:1923)
	at net.minecraft.class_845.run(class_845.java:45)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2107431672 bytes (2009 MB) / 2617769984 bytes (2496 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 1.0.7
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		bannerelytra: BannerElytra 1.0
		bettercompass: Better Compass 2.0.0
		blur: Blur 1.0.5
		brokenxp: Broken XP 1.0.3
		carpet: Carpet Mod in Fabric 1.1.0
		carpet-extra: Carpet Extra 1.2.0
		clear-skies: Clear Skies 1.0.3+build.10
		cleardespawn: Clear Despawn 1.0.4
		cloth: Cloth Events 0.6.0
		cloth-config: Cloth Config 0.2.5
		cloth-config2: Cloth Config v2 1.1.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.3
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.3
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.6
		com_squareup_okhttp3_logging-interceptor: logging-interceptor 3.9.1
		com_squareup_okhttp3_okhttp: okhttp 3.9.1
		com_squareup_okio_okio: okio 1.13.0
		com_vdurmont_emoji-java: emoji-java 4.0.0
		dirttopath: Dirt to Path 1.2.1
		extradiscs: ExtraDiscs 1.1.0+build.6
		fabric: Fabric API 0.4.1+build.245-1.14
		fabric-api-base: Fabric API Base 0.1.1+2ac73e7242
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: fabric-commands-v0 0.1.1+b494ebeb42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.50+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.0+c877038942
		fabric-networking-v0: Fabric Networking (v0) 0.1.3+591e97ae42
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-particles-v1: fabric-particles-v1 0.1.1+c877038942
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.1+c877038942
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabriccontrolling: Fabric Controlling 1.0.1
		fabricloader: Fabric Loader 0.6.2+build.166
		gamemodeoverhaul: GamemodeOverhaul 1.14.4-1.0.1.2
		glassdoor: Glass Doors 1.3.2
		golemhealer: Golem Healer 1.0.0
		heartofthecauldron: Heart of the Cauldron 1.1.0
		iamverysmart: I Am Very Smart 1.5.0+mc1.14.4
		itemscroller: Item Scroller 0.15.0-dev.20190720.190250
		iwanthostilemobsinpeaceful: I Want Hostile Mobs in Peaceful ${version}
		jankson: Jankson 1.0.0+j1.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.5.0
		libcd: LibCapableData 1.3.1+1.14.4
		libmultipart: LibMultiPart 0.2.0
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.2.0
		libnetworkstack: Lib Network Stack 0.2.0
		lightoverlay: Light Overlay 3.6
		litematica: Litematica 0.0.0-dev.20190720.191654
		malilib: MaLiLib 0.10.0-dev.20
		minecraft: Minecraft 1.14.4
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.7.11+build.121
		net_fabricmc_stitch: stitch 0.2.1.61
		nicetohave: Nice to Have 1.2.2
		optifabric: Optifabric 0.5.2
		org_apache_logging_log4j_log4j-api: log4j-api 2.11.0
		org_javacord_javacord-api: javacord-api 3.0.4
		org_javacord_javacord-core: javacord-core 3.0.4
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.50
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.0
		org_json_json: json 20170516
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		recipemod: Recipe Mod 1.0.0
		shulkerboxtooltip: Shulker Box Tootip 1.3.1+1.14.4
		smartermending: Smarter Mending 1.1.0
		sneakthroughberries: Sneak Through Berries 1.14.4-1.1.2-fabric
		snowaccumulation: Snow Accumulation 1.14.4-1.0-fabric
		vanilla_parts: Vanilla Parts 1.0.0
		villagerhats: Villager Hats fabric-1.14.0-1.0.0
	Launched Version: MultiMC5
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Nate's Tweaks
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Juuxel** [comment]
This is a compatibility issue between OptiFine and another mod (not Vanilla Parts, but might be some mod that VP requires).

**Comment by Juuxel** [comment]
Update: this is a bug with Fabric API's Indigo renderer, not caused by Vanilla Parts.
