### ISSUE TITLE
[BUG] Problem with translucent multiblocks

### ISSUE THREAD

**Issue by SconeStone** [Juuxel/VanillaParts#20]
I was using the mod Mo Glass with the possibilty to create glass slabs, but when it turned them in to a multiblock it losses all it's translucentcy. Don't know if you can fix this or not, seems minor.

![2020-11-16_12 15 07](https://user-images.githubusercontent.com/74540562/99246709-101a3580-2806-11eb-8591-70a1ea9a4d0f.png)

**Comment by Juuxel** [comment]
Last time I checked, this was a limitation of LibMultipart. I can take a look whether I can fix this now, though, since LMP might have gotten the functionality I need. Also, duplicate of #4.
