### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by SylisMC** [Juuxel/VanillaParts#22]
I think this might be a duplicate of [issue 21](https://github.com/Juuxel/VanillaParts/issues/21)

Crashed with jumploader & fabric API+ 1.16.4

[Multipart crash.txt](https://github.com/Juuxel/VanillaParts/files/5692473/Multipart.crash.txt)

**Comment by AlexIIL** [comment]
Yes, this is the same LibNetworkStack crash as #21. A temporary fix is to downgrade fabric api to 0.2.7 (suggested here: https://github.com/Juuxel/VanillaParts/issues/21#issuecomment-743031228) until an LNS update has been released.

**Comment by Juuxel** [comment]
Yeah, it's a dupe of #21.
