### ISSUE TITLE
Teleport crash

### ISSUE THREAD

**Issue by srnyx** [Juuxel/VanillaParts#27]
I did /home and this crash occurred: https://pastebin.com/4PXXk3mg

**Comment by AlexIIL** [comment]
Could you upload the full crash report?

**Comment by AlexIIL** [comment]
Also, are you playing in a singleplayer world or on a remote server?

**Comment by srnyx** [comment]
> Also, are you playing in a singleplayer world or on a remote server?

Remote server

**Comment by srnyx** [comment]
> Could you upload the full crash report?

Sorry, I shouldn't have used the word "crash." It just kicked me from the server.

**Comment by AlexIIL** [comment]
Ah ok. In which case I think this is a bug with LibNetworkStack that I haven't fixed for a while - currently LibMultipart data is being sent before the block entity itself is sent, which means that the LMP block entity isn't registered with LNS when it receives the packet.

A temporary workaround would be to open a single-player world (with any multipart placed down - you might want to inspect it with F3) before connecting to the server. However I'll release an updated version of LNS and LMP to properly fix this in the future.

**Comment by srnyx** [comment]
Is this safe to close?
