### ISSUE TITLE
Crash with MoreCulling

### ISSUE THREAD

**Issue by ardissaps** [Juuxel/VanillaParts#29]
https://paste.atlauncher.com/view/c72aa12f-3bf5-43a5-b3bc-18b607dfeb3e

**Comment by Juuxel** [comment]
Thanks for the report. This seems to be an incompatibility between the MoreCulling mod and LibMultipart, a library mod that I use in Vanilla Parts.

**Comment by FxMorin** [comment]
I don't have any plans to change the API at the moment. Here's an example of how to use it: <https://github.com/isXander/CullLessLeaves/tree/compat/moreculling>
You would need to disable your mixin, and then implement your checks through the api to fix this issue

**Comment by Juuxel** [comment]
You're commenting on the wrong project, the mixin isn't in Vanilla Parts but LibMultiPart.

**Comment by ardissaps** [comment]
I choose to use VanillaParts instead, more culling cause issue on 1.18.2, the cull is so aggresive so that it bugged with ice on top of solid block while on adjancent water (causing underground visible from that ice), took hours for me to find out.

**Comment by FxMorin** [comment]
> You're commenting on the wrong project, the mixin isn't in Vanilla Parts but LibMultiPart.

oof
Also yes im no longer working on MoreCulling for 1.18.2, that's been fixed in the 1.19 builds

**Comment by Juuxel** [comment]
The crash seems to be fixed, not that it was a VP issue in the first place.

**Comment by FxMorin** [comment]
It's fixed however VanillaParts wont be culling correctly
