### ISSUE TITLE
Multiblock parts become invisible when using Optfine

### ISSUE THREAD

**Issue by czrptr** [Juuxel/VanillaParts#3]
Using Optifine (+ OptiFabric) and VanillaParts by themselves causes no issues. But when a shader is used than all multiblocks become invisible (their hitboxes are still visible but the parts don't render). I encountered this issue using both a shader with real time shadows (Sildurs Vibrant Shaders Lite) and a shader with no real time shadows (Sildurs basic shaders).

**Comment by Juuxel** [comment]
Optifine is not supported.
