### ISSUE TITLE
1.19/1.19.1/1.19.2 port?

### ISSUE THREAD

**Issue by lostopkk** [Juuxel/VanillaParts#34]
1.19 planned?

**Comment by Juuxel** [comment]
Yes, I'm just waiting for a LibMultipart release on 1.19.

**Comment by AstralOrdana** [comment]
seems close
https://github.com/AlexIIL/LibMultiPart

**Comment by lostopkk** [comment]
@Juuxel libmultipart release today 0.8.0!

**Comment by Juuxel** [comment]
Yep, I noticed - the update is done now.
