### ISSUE TITLE
When reloading assets, textures on multiparts break

### ISSUE THREAD

**Issue by BBftw** [Juuxel/VanillaParts#6]
I'm no expert but it seems like the parts' assigned position on the texture atlas doesn't change when assets are reloaded. This means that when a new texture atlas is generated by the game, the multiparts will show random parts of the texture atlas.
I have optifabric installed running OptiFine 1.14.4 HD U F4.
![2019-12-30_17 54 38](https://user-images.githubusercontent.com/31790318/71571284-a16cb480-2b2d-11ea-83a8-61e57b1ce4c4.png)
![2019-12-30_17 54 28](https://user-images.githubusercontent.com/31790318/71571285-a7fb2c00-2b2d-11ea-9795-09e793e8813c.png)

**Comment by Juuxel** [comment]
The 1.14 build of Vanilla Parts isn't supported anymore, but I suspect that this also happens on 1.15 because of my model cache. I'll look into fixing this.
