### ISSUE TITLE
Fences not compatible with JumpOverFences

### ISSUE THREAD

**Issue by Martmists-GH** [Juuxel/VanillaParts#7]

**Comment by Juuxel** [comment]
This is not a Vanilla Parts issue. Multiparts can't be instances of `FenceBlock`, so there's nothing I can do.

**Comment by Loriborn** [comment]
As mentioned in #8 , fences seem to be causing issues with expected vanilla behavior as well; maybe a config option to enable/disable specific multipart functionality to extend compatibility, at least until vanilla behavior is fully working?
